package com.ntdhtcct.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.util.Objects;
import java.util.UUID;

/**
 * Entity ánh xạ bảng roles.
 */
@Entity
@Table(name = "roles")
public class Role {

    /** Maximum allowed length for a role name. */
    private static final int NAME_MAX_LENGTH = 50;

    /** Unique role identifier generated by the persistence provider. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /** Unique name of the role. */
    @Column(name = "name", nullable = false, unique = true,
            length = NAME_MAX_LENGTH)
    private String name;

    /** Creates an empty role for persistence. */
    public Role() {
    }

    /**
     * Creates a role with the supplied name.
     *
     * @param roleName unique role name
     */
    public Role(final String roleName) {
        this.name = roleName;
    }

    /**
     * Returns this role's identifier.
     *
     * @return the identifier, or {@code null} before persistence
     * @implSpec Returns the identifier assigned to this entity by persistence.
     */
    public UUID getId() {
        return id;
    }

    /**
     * Sets this role's identifier.
     *
     * @param roleId identifier to assign
     * @implSpec Replaces the identifier stored by this entity.
     */
    public void setId(final UUID roleId) {
        this.id = roleId;
    }

    /**
     * Returns this role's name.
     *
     * @return the role name
     * @implSpec Returns the name stored by this entity.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets this role's name.
     *
     * @param roleName name to assign
     * @implSpec Replaces the name stored by this entity.
     */
    public void setName(final String roleName) {
        this.name = roleName;
    }

    /**
     * Compares this role with another object using the role identifier.
     *
     * @param other object to compare
     * @return {@code true} when both objects have the same role identifier
     * @implSpec Equality is based only on the identifier.
     */
    @Override
    public boolean equals(final Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Role role)) {
            return false;
        }
        return Objects.equals(id, role.id);
    }

    /**
     * Computes this role's hash code from its identifier.
     *
     * @return the hash code
     * @implSpec The hash code is based only on the identifier.
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
